---
# Filebeat defaults

# Версия Filebeat
filebeat_version: "8.x"

# Elasticsearch
filebeat_elasticsearch_hosts: "http://elastic.ru-central1.internal:9200"

# Kibana
filebeat_kibana_host: "http://kibana.ru-central1.internal:5601"

# Nginx module
filebeat_nginx_access_log: "/var/log/nginx/access.log*"
filebeat_nginx_error_log: "/var/log/nginx/error.log*"
